import os

# Database configuration
DATABASE_USER = 'root'
DATABASE_PASSWORD = 'Radhekrishn..'
DATABASE_NAME = 'recipe'
DATABASE_HOST = 'localhost'
DATABASE_PORT = '3306'

SQLALCHEMY_DATABASE_URI = f'mysql+mysqlconnector://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
